name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r pacman_game/requirements.txt
        pip install pyinstaller
        
    - name: Build with PyInstaller
      run: |
        cd pacman_game
        pyinstaller --onefile --windowed pacman.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: pacman-windows
        path: pacman_game/dist/pacman.exe
